"""init schema

Revision ID: b3a873efa5b1
Revises: 
Create Date: 2026-08-29 04:33:02.065823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b3a873efa5b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='onboarding', nullable=False),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('tg_bot_token', sa.Text(), nullable=True),
    sa.Column('max_bot_token', sa.Text(), nullable=True),
    sa.Column('channel_priority', postgresql.ARRAY(sa.Text()), server_default='{tg,max,sms}', nullable=False),
    sa.Column('avg_check', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('work_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remind_offsets_h', postgresql.ARRAY(sa.Integer()), server_default='{24,3}', nullable=False),
    sa.Column('sms_limit_month', sa.Integer(), server_default='300', nullable=False),
    sa.Column('texts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Europe/Moscow', nullable=False),
    sa.Column('feature_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('next_payment_at', sa.Date(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), server_default='0', nullable=False),
    sa.Column('admin_tg_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('onboarding', 'active', 'grace', 'paused', 'archived')", name='salons_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialog_state',
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('ext_id', sa.BigInteger(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('salon_id', 'channel', 'ext_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('repeat_cycle_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('work_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('pass_hash', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('invite_token_hash', sa.Text(), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'staff', 'superadmin')", name='users_role_check'),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_support', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_salon_created', 'audit_log', ['salon_id', 'created_at'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('max_id', sa.BigInteger(), nullable=True),
    sa.Column('last_visit_at', sa.Date(), nullable=True),
    sa.Column('last_service_id', sa.Integer(), nullable=True),
    sa.Column('do_not_disturb', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_outreach_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('salon_id', 'phone', name='customers_salon_phone_key')
    )
    op.create_table('sessions',
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acting_salon_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acting_salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('source', sa.Text(), server_default='bot', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('rescheduled_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'reminded_24h', 'reminded_sms', 'confirmed', 'done', 'rescheduled', 'cancelled', 'no_show')", name='bookings_status_check'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_to_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_salon_starts_status', 'bookings', ['salon_id', 'starts_at', 'status'], unique=False)
    op.create_table('waitlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('wanted_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wanted_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('salon_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('delivery_status', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel IN ('tg', 'max', 'sms')", name='message_log_channel_check'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['salon_id'], ['salons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_log_salon_sent', 'message_log', ['salon_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_log_salon_sent', table_name='message_log')
    op.drop_table('message_log')
    op.drop_table('waitlist')
    op.drop_index('ix_bookings_salon_starts_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('sessions')
    op.drop_table('customers')
    op.drop_index('ix_audit_log_salon_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('staff')
    op.drop_table('services')
    op.drop_table('payments')
    op.drop_table('dialog_state')
    op.drop_table('salons')
    # ### end Alembic commands ###
