"""indexes for foreign keys and hot filters

Revision ID: ca491653a4cc
Revises: b3a873efa5b1
Create Date: 2026-08-29 16:46:54.977099

"""
from alembic import op
import sqlalchemy as sa


revision = 'ca491653a4cc'
down_revision = 'b3a873efa5b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bookings_customer', 'bookings', ['customer_id', 'starts_at'], unique=False)
    op.create_index('ix_bookings_service', 'bookings', ['service_id'], unique=False)
    op.create_index('ix_bookings_staff', 'bookings', ['staff_id'], unique=False)
    op.create_index('ix_customers_last_service', 'customers', ['last_service_id'], unique=False)
    op.create_index('ix_customers_salon_tg', 'customers', ['salon_id', 'tg_id'], unique=False)
    op.create_index('ix_message_log_booking_kind', 'message_log', ['booking_id', 'kind'], unique=False)
    op.create_index('ix_message_log_customer_sent', 'message_log', ['customer_id', 'sent_at'], unique=False)
    op.create_index('ix_payments_salon_period', 'payments', ['salon_id', 'period_start'], unique=False)
    op.create_index('ix_services_salon', 'services', ['salon_id'], unique=False)
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_index('ix_staff_salon', 'staff', ['salon_id'], unique=False)
    op.create_index('ix_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index('ix_users_invite_token', 'users', ['invite_token_hash'], unique=False)
    op.create_index('ix_users_salon', 'users', ['salon_id'], unique=False)
    op.create_index('ix_waitlist_salon_wanted', 'waitlist', ['salon_id', 'wanted_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_waitlist_salon_wanted', table_name='waitlist')
    op.drop_index('ix_users_salon', table_name='users')
    op.drop_index('ix_users_invite_token', table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_index('ix_staff_salon', table_name='staff')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_index('ix_services_salon', table_name='services')
    op.drop_index('ix_payments_salon_period', table_name='payments')
    op.drop_index('ix_message_log_customer_sent', table_name='message_log')
    op.drop_index('ix_message_log_booking_kind', table_name='message_log')
    op.drop_index('ix_customers_salon_tg', table_name='customers')
    op.drop_index('ix_customers_last_service', table_name='customers')
    op.drop_index('ix_bookings_staff', table_name='bookings')
    op.drop_index('ix_bookings_service', table_name='bookings')
    op.drop_index('ix_bookings_customer', table_name='bookings')
    # ### end Alembic commands ###
